import React, {useEffect, useLayoutEffect, useRef, useState} from 'react';
import {AbsoluteFill, Img, Sequence, Audio, staticFile, useCurrentFrame, delayRender, continueRender, cancelRender} from 'remotion';
import {SkinViewer} from 'skinview3d';

export const FPS=30, DURATION=1950;
const BLUE='#007aff', PURPLE='#af52de';
const clamp=(x:number)=>Math.max(0,Math.min(1,x));
const out=(x:number)=>1-Math.pow(1-clamp(x),4);
const smooth=(x:number)=>{x=clamp(x);return x*x*(3-2*x)};
const lerp=(a:number,b:number,p:number)=>a+(b-a)*p;
const at=(f:number,start:number,end:number)=>clamp((f-start)/(end-start));
const kf=(p:number,keys:number[][])=>{for(let i=1;i<keys.length;i++){if(p<=keys[i][0])return lerp(keys[i-1][1],keys[i][1],at(p,keys[i-1][0],keys[i][0]));}return keys[keys.length-1][1]};
const reveal=(f:number,start=0,offset=35)=>({opacity:out(at(f,start,start+28)),transform:`translateY(${(1-out(at(f,start,start+34)))*offset}px)`});
const Logo=({size=36,style={}}:{size?:number;style?:React.CSSProperties})=><Img src={staticFile('logo.png')} style={{width:size,height:size,objectFit:'contain',...style}}/>;
type IconName='play'|'folder'|'download'|'user'|'logs'|'gear'|'spark'|'cube'|'check'|'pack'|'arrow';
function Icon({name='spark',size=30,color='currentColor'}:{name?:IconName,size?:number,color?:string}){
 const paths:Record<IconName,React.ReactNode>={
 play:<path d="M8 4l14 12L8 28z" fill={color} stroke="none"/>,folder:<path d="M3 8h10l3 4h13v15H3z"/>,download:<><path d="M16 3v18m-7-7l7 7 7-7M4 25v4h24v-4"/></>,user:<><circle cx="16" cy="9" r="5"/><path d="M5 29c0-8 22-8 22 0z"/></>,logs:<><rect x="5" y="4" width="22" height="25" rx="3"/><path d="M10 10h12m-12 6h12m-12 6h7"/></>,gear:<><circle cx="16" cy="16" r="6"/><path d="M16 2v4m0 20v4M2 16h4m20 0h4M6 6l3 3m14 14 3 3M6 26l3-3M23 9l3-3"/></>,spark:<path d="M16 1l4 11 11 4-11 4-4 11-4-11-11-4 11-4z"/>,cube:<><path d="M16 2L29 9v15l-13 7-13-7V9zM3 9l13 8 13-8M16 17v14"/></>,check:<path d="M5 16l7 7L27 7"/>,pack:<><path d="M4 10l12-7 12 7v17H4zM4 10h24M16 10v17"/><path d="M10 6l12 4"/></>,arrow:<path d="M4 16h24M19 7l9 9-9 9"/>
 };
 return <svg width={size} height={size} viewBox="0 0 32 32" fill="none" stroke={color} strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" style={{flexShrink:0}}>{paths[name]}</svg>
}
function Background({light=false,f=0}:{light?:boolean;f?:number}){
 return <AbsoluteFill style={{background:light?'#f4f6fa':'#070a12'}}><AbsoluteFill style={{background:`radial-gradient(ellipse at ${lerp(20,38,clamp(f/220))}% 75%,${light?'#dfeaff':'#08244d'} 0,transparent 55%),radial-gradient(ellipse at 83% 25%,${light?'#eee5ff':'#211238'} 0,transparent 55%)`,opacity:light?.74:.8}}/></AbsoluteFill>
}
function TopBar({ai=false,compact=false}:{ai?:boolean;compact?:boolean}){return <div className="bar"><div className="dots"><i/><i/></div><div className="brand"><Logo size={30}/><div>Novaina <span>Launcher</span></div></div>{!ai&&!compact&&<div style={{display:'flex',gap:27,margin:'auto'}}>{(['play','folder','download','user','logs','gear'] as IconName[]).map(x=><Icon name={x} key={x} size={23} color={BLUE}/>)}</div>}<div className="ai-switch"><span className="gradient">AI Mode</span><i className={'switch '+(ai?'on':'')}/></div></div>}
function Window({children,light=false,ai=false,style={}}:{children:React.ReactNode;light?:boolean;ai?:boolean;style?:React.CSSProperties}){return <div className={'window '+(light?'light':'')} style={style}><TopBar ai={ai} compact={Number(style.width)<1000}/>{children}</div>}
function SideBar({active='启动'}:{active?:string}){return <div className="sidebar">{[['play','启动'],['folder','版本'],['download','下载'],['user','账户'],['logs','日志'],['gear','设置']].map(([i,t])=><div className={'nav '+(active===t?'active':'')} key={t}><Icon name={i as IconName} size={23}/>{t}</div>)}</div>}
function Head({f,title,tag,light=false,style={}}:{f:number;title:string;tag:string;light?:boolean;style?:React.CSSProperties}){return <div style={{position:'absolute',left:140,top:85,color:light?'#171c29':'#f7f9ff',...style}}><div className="eyebrow" style={{...reveal(f,0),marginBottom:20}}>{tag}</div><h1 className="headline" style={reveal(f,7)}>{title}</h1></div>}
function Home({f=0,light=true,dim=false}:{f?:number;light?:boolean;dim?:boolean}){return <div style={{display:'flex',height:'calc(100% - 66px)',opacity:dim?.72:1}}><SideBar/><div className="content"><div style={{fontSize:34,fontWeight:700,marginBottom:40}}>你好，Nova</div><div style={{display:'flex',gap:22,marginTop:16}}>{[['当前账户','Nova','Microsoft'],['游戏版本','新星冒险','Fabric · 1.20.1'],['运行环境','Java 17','智能内存 · 4 GB']].map(([label,name,meta],i)=><div className="card" key={label} style={{flex:1,height:258,...reveal(f,i*5)}}><div className="label" style={{display:'flex',alignItems:'center',gap:10,marginBottom:25}}><Icon name={(['user','folder','gear'] as IconName[])[i]} size={22} color={BLUE}/>{label}</div>{i===0?<div style={{height:63,display:'flex',alignItems:'center',gap:17,marginBottom:14}}><SteveHead size={58}/><div className="card-title">{name}</div></div>:<div className="card-title" style={{marginTop:45,marginBottom:18}}>{name}</div>}<span className="pill">{meta}</span><div className="btn" style={{marginTop:23,height:40,fontSize:16}}>{['管理账户','选择版本','Java 设置'][i]}</div></div>)}</div><div className="card" style={{marginTop:35,display:'flex',alignItems:'center',padding:'20px 24px'}}><span style={{fontSize:21,fontWeight:600}}>就绪</span><div className="btn primary" style={{marginLeft:'auto',gap:10}}><Icon name="play" size={18}/>启动游戏</div></div></div></div>}
function SteveHead({size=56}:{size?:number}){return <div style={{width:size,height:size,borderRadius:13,overflow:'hidden',position:'relative',flexShrink:0,background:'#86715d'}}><Img src={staticFile('steve.png')} style={{position:'absolute',width:size*8,height:size*8,left:-size,top:-size,imageRendering:'pixelated'}}/></div>}

function Intro({f}:{f:number}){
 const p=f/84;const expansion=out(at(p,.355,.95));const flash=kf(p,[[0,0],[.34,0],[.385,.9],[.50,0]]);
 return <AbsoluteFill style={{background:'#090d17'}}><AbsoluteFill style={{background:'radial-gradient(ellipse at center,#13233a 0,transparent 65%)',opacity:.35}}/>
 {[BLUE,PURPLE].map((c,i)=><div key={c} style={{position:'absolute',width:500,height:500,left:710,top:290,borderRadius:'50%',background:`radial-gradient(ellipse at ${i?60:42}% 50%,${c}b0,${c}50 30%,${c}00 68%)`,opacity:kf(p,i?[[0,0],[.21,.12],[.34,.18],[.50,.95],[.78,.35],[1,0]]:[[0,0],[.16,.18],[.34,.22],[.47,1],[.72,.48],[1,0]]),transform:`scale(${lerp(.3,7.4,expansion)})`}}/>)}
 <div style={{position:'absolute',width:250,height:250,left:835,top:415,borderRadius:'50%',border:'2px solid #7e7aff',opacity:kf(p,[[0,0],[.36,0],[.395,.6],[.62,.2],[.88,0]]),transform:`scale(${lerp(.7,12,out(at(p,.36,.9)))})`}}/>
 <div style={{position:'absolute',left:830,top:410,width:260,height:260,borderRadius:'50%',background:'radial-gradient(circle,#effaff,#7e9eff77 30%,#af52de00 65%)',opacity:flash,transform:`scale(${lerp(.3,2.7,out(at(p,.345,.57)))})`}}/>
 <Logo size={245} style={{position:'absolute',left:837.5,top:417.5,opacity:kf(p,[[0,0],[.16,1],[.21,1],[.24,.38],[.275,1],[.36,1],[.395,0]]),transform:`scale(${kf(p,[[0,.86],[.18,1.025],[.31,1],[.37,1.08],[.44,1.32]])})`}}/>
 {Array.from({length:64},(_,i)=>{const x=i%8,y=Math.floor(i/8),dx=x-3.5,dy=y-3.5,ang=Math.atan2(dy,dx)+Math.sin(i*7.31)*.16,spread=Math.abs(Math.sin(i*2.3)),dist=2203*(.38+spread*.24)*out(at(p,.38,.95)),a=kf(p,[[0,0],[.365,0],[.38,1],[.46,1],[.78+spread*.15,0]]);return <div key={i} style={{position:'absolute',left:837.5+x*30.625,top:417.5+y*30.625,width:30.9,height:30.9,overflow:'hidden',opacity:a,transform:`translate(${Math.cos(ang)*dist}px,${Math.sin(ang)*dist}px) rotate(${dist/30*Math.sin(i)}deg)`}}><Logo size={245} style={{position:'absolute',left:-x*30.625,top:-y*30.625}}/></div>})}
 </AbsoluteFill>
}
function Hero({f}:{f:number}){return <AbsoluteFill><Background f={f}/><div style={{position:'absolute',left:0,top:95,width:'100%',textAlign:'center'}}><Logo size={230} style={{...reveal(f,0,45),transform:`translateY(${lerp(45,0,out(at(f,0,35)))}px) scale(${lerp(.85,1,out(at(f,0,42)))})`}}/><div style={{fontSize:174,letterSpacing:-9,fontWeight:650,marginTop:10,...reveal(f,9)}}>Novaina</div><div style={{fontSize:31,letterSpacing:11,color:'#93a8d1',margin:'8px 0 37px',...reveal(f,18)}}>LAUNCHER</div><div style={{fontSize:54,letterSpacing:-2,fontWeight:600,...reveal(f,28)}}>从一句想法，到整个世界。</div><div className="gradient" style={{fontSize:23,letterSpacing:3,marginTop:36,...reveal(f,45)}}>INTRODUCING NOVAINA 1.0</div></div><div style={{position:'absolute',bottom:0,width:'100%',height:170,background:'linear-gradient(0deg,#14245155,transparent)'}}/></AbsoluteFill>}
function Overview({f}:{f:number}){const p=smooth(at(f,0,162));return <AbsoluteFill><Background light f={f}/><Head f={f} light title="进入世界，更简单。" tag="YOUR WORLD. READY."/><Window light style={{position:'absolute',width:1500,height:625,left:210,top:340,opacity:out(at(f,8,38)),transform:`perspective(2100px) translateY(${lerp(85,-6,out(at(f,8,70)))}px) rotateX(${lerp(8,2,p)}deg) rotateY(${lerp(-9,2,p)}deg) scale(${lerp(.94,1.03,p)})`}}><Home f={f-25}/></Window></AbsoluteFill>}
function Download({f}:{f:number}){const part=f<77?0:1;return <AbsoluteFill><Background light f={f}/><Head f={f} light title="发现你的下一种可能。" tag="GAMES · MODS · MODPACKS"/><Window light style={{position:'absolute',width:1410,height:630,left:255,top:323,opacity:out(at(f,9,36)),transform:`perspective(2200px) rotateY(${lerp(6,-3,smooth(f/150))}deg) rotateX(3deg)`}}><div style={{display:'flex',height:564}}><SideBar active="下载"/><div style={{padding:'29px 52px',flex:1}}><div style={{fontSize:36,fontWeight:700,marginBottom:23}}>{part===0?'为新的世界而来。':'选择一种玩法。'}</div>{part===0?<div style={{display:'grid',gap:16,width:900}}>{[['play','游戏版本','原版与主流加载器'],['cube','模组','发现更多可能'],['pack','整合包','打开完整冒险']].map(([icon,title,sub],i)=><div key={title} className="entry" style={{minHeight:99,padding:'18px 24px',...reveal(f,14+i*6,55)}}><div style={{width:54,height:54,borderRadius:16,background:'#007aff12',display:'grid',placeItems:'center',color:BLUE}}><Icon name={icon as IconName} size={30}/></div><div><div className="card-title" style={{fontSize:26}}>{title}</div><div className="label" style={{fontSize:16}}>{sub}</div></div><div className="arrow">›</div></div>)}</div>:<div style={{...reveal(f-77,0,30)}}><div className="pill" style={{marginBottom:20,fontSize:19}}>Minecraft 1.20.1</div><div style={{display:'flex',gap:15}}>{['原版','Forge','Fabric','NeoForge'].map((x,i)=><div key={x} className="card" style={{width:198,height:184,borderColor:i===2?BLUE:undefined,background:i===2?'#007aff0c':undefined,textAlign:'center',padding:22}}><Icon name={i===0?'play':i===1?'gear':i===2?'logs':'spark'} size={45} color={BLUE}/><div style={{fontSize:24,marginTop:14,fontWeight:600}}>{x}</div>{i===2&&<div style={{fontSize:15,color:BLUE,marginTop:10}}>已选择</div>}</div>)}</div><div className="card" style={{marginTop:23,padding:18,display:'flex',justifyContent:'space-between',alignItems:'center'}}><span className="label">镜像优先 · Java 自动配置</span><div className="btn primary">继续 →</div></div></div>}</div></div></Window></AbsoluteFill>}
const danmakuMessages=[['已准备 Java 17','环境就绪'],['资源校验完成','下载完成'],['正在启动「新星冒险」','启动中'],['Fabric 模组已加载','24 个模组'],['欢迎进入你的世界','启动成功']];
function Danmaku({f}:{f:number}){return <AbsoluteFill><Background f={f}/><Head f={f} title="每一步，都看得见。" tag="LOGS, IN MOTION."/><Window style={{position:'absolute',width:1460,height:625,left:230,top:310,opacity:out(at(f,10,40)),transform:`perspective(1800px) rotateX(4deg) rotateY(${lerp(-3,3,smooth(f/170))}deg) scale(.98)`}}><Home light={false} f={150} dim/></Window><div style={{position:'absolute',left:0,top:350,width:1920,height:460,overflow:'hidden'}}>{danmakuMessages.map(([text,tag],i)=>{const p=at(f,15+i*18,140+i*18),x=lerp(1960,-650,smooth(p));return <div key={text} style={{position:'absolute',top:25+(i%3)*120,left:x,opacity:out(at(f,15+i*18,30+i*18)),padding:'24px 34px',fontSize:30,fontWeight:600,display:'flex',gap:19,alignItems:'center',whiteSpace:'nowrap',borderRadius:24,border:'1px solid #7b99ca66',background:'linear-gradient(120deg,#162c46ee,#29324dee)',boxShadow:'0 15px 50px #0005'}}><div style={{color:i===4?'#57e4be':'#6cacff'}}><Icon name={i===4?'check':'logs'} size={28}/></div>{text}<span style={{fontSize:18,color:'#9baaca',paddingLeft:8}}>{tag}</span></div>})}</div><div style={{position:'absolute',bottom:85,left:0,width:'100%',textAlign:'center',fontSize:27,color:'#b5c2db',...reveal(f,65)}}>运行日志，化作流动的弹幕。</div></AbsoluteFill>}

function Skin({f,width=510,height=620}:{f:number;width?:number;height?:number}){
 const canvas=useRef<HTMLCanvasElement>(null);const viewer=useRef<SkinViewer|null>(null);const [ready,setReady]=useState(false);const [handle]=useState(()=>delayRender('Loading bundled Steve skin'));
 useEffect(()=>{const v=new SkinViewer({canvas:canvas.current!,width,height,renderPaused:true,enableControls:false,zoom:.86,fov:40});viewer.current=v;v.camera.position.set(14,7,57);v.camera.lookAt(0,0,0);v.loadSkin(staticFile('steve.png'),{model:'default'}).then(()=>{setReady(true);continueRender(handle)}).catch(e=>cancelRender(e));return ()=>{v.dispose();viewer.current=null}},[]);
 useLayoutEffect(()=>{if(!ready||!viewer.current)return;const v=viewer.current;v.playerObject.rotation.y=lerp(-.55,1.65,smooth(at(f,0,189)));v.playerObject.skin.head.rotation.y=Math.sin(f/65)*.13;v.playerObject.skin.rightArm.rotation.z=.1;v.playerObject.skin.leftArm.rotation.z=-.1;v.playerObject.position.y=Math.sin(f/45)*.3;v.render();},[ready,f]);
 return <canvas ref={canvas} style={{width,height,position:'relative'}}/>;
}
function Skins({f}:{f:number}){return <AbsoluteFill><Background light f={f}/><div style={{position:'absolute',left:140,top:240,color:'#171c29'}}><div className="eyebrow" style={reveal(f)}>LIVE 3D SKIN PREVIEW</div><h1 className="headline" style={{fontSize:99,marginTop:30,...reveal(f,8)}}>你的形象。<br/>立体呈现。</h1><div className="caption" style={{marginTop:38,color:'#6c788d',...reveal(f,23)}}>Microsoft · LittleSkin · 离线账户</div><div style={{display:'flex',gap:14,marginTop:45,...reveal(f,37)}}><SteveHead size={65}/><div><div style={{fontSize:27,fontWeight:600}}>Nova</div><div className="label">Microsoft 账户</div></div></div></div><Window light style={{position:'absolute',left:945,top:140,width:765,height:795,opacity:out(at(f,10,38)),transform:`perspective(2200px) rotateY(${lerp(-9,-2,smooth(f/189))}deg) rotateX(2deg)`}}><div style={{height:730,position:'relative',background:'radial-gradient(ellipse at 50% 65%,#dce8ff77,transparent 65%)'}}><div style={{position:'absolute',left:34,top:28,fontSize:25,fontWeight:650}}>皮肤预览</div><div style={{position:'absolute',left:125,top:64}}><Skin f={f}/></div><div style={{position:'absolute',width:325,height:48,borderRadius:'50%',background:'radial-gradient(ellipse,#879eca55,transparent 70%)',left:220,top:579}}/><div style={{position:'absolute',bottom:34,left:0,width:'100%',display:'flex',justifyContent:'center',gap:12}}>{['导入','刷新','导出'].map(x=><div className="btn" key={x}>{x}</div>)}</div></div></Window><div style={{position:'absolute',right:115,bottom:53,color:'#7183a0',fontSize:19,...reveal(f,45)}}>旋转 · 缩放 · 实时预览</div></AbsoluteFill>}
function AiReveal({f}:{f:number}){const second=f>=44;return <AbsoluteFill><Background f={f}/><AbsoluteFill style={{background:`radial-gradient(ellipse at 28% 65%,#007aff55,transparent 60%),radial-gradient(ellipse at 78% 28%,#af52de55,transparent 55%)`,opacity:out(f/45)}}/><div style={{position:'absolute',top:178,left:0,width:'100%',textAlign:'center'}}><div className="gradient" style={{fontSize:28,letterSpacing:7,...reveal(f)}}>AI MODE</div><div style={{fontSize:144,letterSpacing:-8,fontWeight:700,marginTop:108,opacity:second?out((f-44)/20):1-at(f,29,44),transform:`translateY(${second?lerp(55,0,out((f-44)/35)):lerp(45,-30,out(f/44))}px)`}}>{second?'开始，指挥。':'不止启动。'}</div><div style={{fontSize:35,color:'#c3c2e2',marginTop:30,...reveal(f,56)}}>让智能，遍布你的世界。</div></div></AbsoluteFill>}
function AiWindow({children,f,style={}}:{children:React.ReactNode;f:number;style?:React.CSSProperties}){return <Window ai style={{position:'absolute',width:1500,height:690,left:210,top:288,opacity:out(at(f,0,26)),...style}}>{children}</Window>}
function AiComposer({text,typing=false}:{text:string;typing?:boolean}){return <div className="composer"><div style={{minHeight:52,lineHeight:1.6}}>{text}{typing&&<span style={{color:'#947bff',marginLeft:3}}>|</span>}</div><div style={{display:'flex',alignItems:'center',marginTop:16}}><div className="btn" style={{fontSize:17,height:37}}>DeepSeek <span style={{marginLeft:40,color:'#8996ab'}}>⌄</span></div><div style={{marginLeft:'auto',width:44,height:44,borderRadius:22,background:'linear-gradient(115deg,#007aff,#af52de)',display:'grid',placeItems:'center',fontSize:26}}>↑</div></div></div>}
function ChoicePointer({f}:{f:number}){
 const x=kf(f,[[0,1490],[17,1490],[48,400],[59,400],[85,1090],[100,1090],[132,1350],[158,1350]]),y=kf(f,[[0,635],[17,635],[48,295],[59,295],[85,295],[100,295],[132,543],[158,543]]);
 return <div style={{position:'absolute',left:x,top:y,opacity:out(at(f,13,27))*(1-at(f,144,158)),pointerEvents:'none'}}>{[48,85,132].map(c=>{const p=at(f,c,c+20);return f>=c&&f<c+20?<div key={c} style={{position:'absolute',left:-25,top:-25,width:55,height:55,border:'2px solid #9c83ff',borderRadius:'50%',opacity:1-p,transform:`scale(${lerp(.3,1.8,out(p))})`}}/>:null})}<svg width="32" height="40" viewBox="0 0 32 40" style={{filter:'drop-shadow(0 3px 5px #0008)',transform:`scale(${f%100===48?.85:1})`}}><path d="M3 2l24 23-12 1-6 11z" fill="#fff" stroke="#252936" strokeWidth="2" strokeLinejoin="round"/></svg></div>
}
const request='帮我打造一个 1.20.1 冒险整合包，加入地图与性能优化。';
function AiPrompt({f}:{f:number}){const text=request.slice(0,Math.round(request.length*out(at(f,28,120))));const sent=f>140;return <AbsoluteFill><Background f={f}/><Head f={f} title="你说一句。" tag="ONE IDEA. MANY POSSIBILITIES."/><AiWindow f={f} style={{transform:`perspective(2400px) rotateX(${lerp(3,0,smooth(f/200))}deg) scale(${lerp(.98,1.02,smooth(f/200))})`}}><div style={{width:1200,margin:'36px auto'}}><div style={{fontSize:20,color:'#9babc7',marginBottom:25}}>新对话</div><div style={{height:270,display:'flex',flexDirection:'column',justifyContent:'center'}}>{sent?<><div style={{alignSelf:'flex-end',maxWidth:970,borderRadius:24,padding:'24px 30px',background:'linear-gradient(105deg,#183151,#2c2042)',fontSize:28,lineHeight:1.6,...reveal(f-140)}}>{request}</div><div style={{display:'flex',gap:16,alignItems:'center',marginTop:29,...reveal(f-140,15)}}><Logo size={35}/><span style={{fontSize:26}}>先确定你的冒险方向。</span></div></>:<div style={{textAlign:'center'}}><Logo size={80}/><div style={{fontSize:40,fontWeight:600,marginTop:18}}>今天，想创造什么？</div></div>}</div><div style={{marginTop:20}}><AiComposer text={sent?'告诉我，你想怎么玩…':text||' '} typing={!sent}/></div></div></AiWindow><div style={{position:'absolute',right:145,top:171,fontSize:29,color:'#aba9cc',...reveal(f,80)}}>剩下的，交给它。</div></AbsoluteFill>}
function AiQuestions({f}:{f:number}){const selected=f>48;return <AbsoluteFill><Background f={f}/><Head f={f} title="先理解，再行动。" tag="A CONVERSATION THAT GETS YOU."/><AiWindow f={f} style={{transform:`perspective(2400px) translateX(${lerp(0,-20,smooth(at(f,25,130)))}px) translateY(${lerp(0,18,smooth(at(f,25,130)))}px) rotateY(${lerp(4,-1,smooth(f/165))}deg) scale(${lerp(.98,1.12,smooth(at(f,20,130)))})`}}><div style={{padding:'36px 75px'}}><div style={{display:'flex',gap:14,alignItems:'center',fontSize:23,marginBottom:28}}><Logo size={35}/>需要你的选择</div><div style={{display:'flex',gap:25}}>{[['想玩什么类型？','探索与冒险','科技与自动化'],['选择游戏版本','Minecraft 1.20.1','Minecraft 1.21.1']].map(([q,a,b],i)=><div className="card" key={q} style={{flex:1,padding:27,...reveal(f,i*10+8)}}><div style={{fontSize:28,fontWeight:650,marginBottom:24}}>{q}</div>{[a,b].map((label,j)=><div key={label} className={'answer '+(f>(i===0?48:85)&&j===0?'selected':'')} style={{marginBottom:12,fontSize:24,display:'flex',alignItems:'center',gap:13}}>{f>(i===0?48:85)&&j===0?<span className="check">✓</span>:<span style={{width:25,height:25,border:'1px solid #8390a5',borderRadius:14}}/>}{label}{j===0&&<span className="gradient" style={{fontSize:15,marginLeft:'auto'}}>推荐</span>}</div>)}<div className="label" style={{marginTop:18}}>自定义回答　__________</div></div>)}</div><div style={{display:'flex',justifyContent:'flex-end',marginTop:24}}><div className="btn primary" style={{background:selected?'linear-gradient(110deg,#007aff,#af52de)':undefined}}>继续 →</div></div></div><ChoicePointer f={f}/></AiWindow></AbsoluteFill>}
function AiExecute({f}:{f:number}){const overall=lerp(12,100,smooth(at(f,20,177)));const rows=[['folder','准备 Minecraft 1.20.1',24],['download','安装 Fabric 与所选模组',72],['gear','配置 Java 与智能内存',118],['check','校验完成，整合包已就绪',153]] as const;return <AbsoluteFill><Background f={f}/><Head f={f} title="它来执行。你来期待。" tag="PLAN. DOWNLOAD. CONFIGURE. VERIFY."/><AiWindow f={f} style={{transform:`perspective(2200px) translateY(${lerp(0,14,smooth(at(f,50,160)))}px) rotateY(${lerp(-5,1,smooth(f/189))}deg) scale(${lerp(.98,1.09,smooth(at(f,30,180)))})`}}><div style={{padding:'34px 90px'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:20}}><div style={{fontSize:28,fontWeight:600}}>正在构建「新星冒险」</div><div className="gradient" style={{fontSize:27,fontWeight:700}}>{Math.floor(overall)}%</div></div><div className="progress" style={{height:13,marginBottom:19}}><div style={{width:overall+'%'}}/></div>{rows.map(([icon,label,start],i)=>{const done=f>start+25;const visible=f>start-18;return <div className="task-row" key={label} style={{opacity:visible?1:.28,transform:`translateX(${visible?0:18}px)`}}><div className="task-icon" style={{color:done?'#6de5c8':undefined}}><Icon name={done?'check':icon} size={24}/></div><div style={{flex:1,fontSize:25,fontWeight:500}}>{label}</div><div style={{fontSize:18,color:done?'#6de5c8':'#9eabc4'}}>{done?'完成':visible?'处理中':'等待'}</div></div>})}<div className="label" style={{marginTop:23,fontSize:17}}>24 个模组 · 隔离目录 · 国内镜像优先</div></div></AiWindow></AbsoluteFill>}
function AiResult({f}:{f:number}){const exported=f>54;return <AbsoluteFill><Background light f={f}/><Head f={f} light title="一个想法。一个完整世界。" tag="YOUR WORLD, CREATED." style={{left:115}}/><Window light ai style={{position:'absolute',width:1490,height:650,left:215,top:312,opacity:out(at(f,0,25)),transform:`perspective(2300px) rotateX(2deg) rotateY(${lerp(-3,0,smooth(f/132))}deg)`}}><div style={{padding:'44px 75px',display:'flex',gap:45}}><div className="card" style={{width:635,height:417,background:'linear-gradient(145deg,#e3edff99,#ede8ffbb)'}}><div style={{display:'flex',alignItems:'center',gap:13}}><Icon name="check" color={BLUE} size={26}/><span className="pill">整合包已就绪</span></div><div style={{fontSize:55,fontWeight:700,margin:'38px 0 20px'}}>新星冒险</div><div style={{display:'flex',gap:9,marginBottom:23}}><span className="pill">1.20.1</span><span className="pill">Fabric</span><span className="pill">24 Mod</span></div><div className="label" style={{fontSize:21}}>Java 17 · 智能内存</div><div className="btn primary" style={{width:160,marginTop:30}}>启动游戏 →</div></div><div style={{flex:1,display:'flex',flexDirection:'column',justifyContent:'center'}}><div style={{fontSize:31,fontWeight:650}}>再一句话，让世界流动。</div><div className="answer" style={{fontSize:25,marginTop:28,lineHeight:1.6,borderColor:'#c9d5e9',background:'#fff9'}}>“把它导出成整合包，发给朋友。”</div><div className="card" style={{marginTop:25,display:'flex',alignItems:'center',gap:18,...reveal(f,48)}}><div style={{color:BLUE}}><Icon name={exported?'check':'pack'} size={32}/></div><div><div style={{fontSize:26,fontWeight:600}}>{exported?'整合包已导出':'正在导出整合包'}</div><div className="label" style={{fontSize:18,marginTop:5}}>新星冒险.zip</div></div></div></div></div></Window></AbsoluteFill>}
function Capabilities({f}:{f:number}){const items=['分析启动日志','自动配置 Java','智能分配内存','管理你的模组','导出整合包','启动游戏'];return <AbsoluteFill><Background f={f}/><div style={{position:'absolute',left:140,top:160}}><div className="eyebrow" style={reveal(f)}>INTELLIGENCE, EVERYWHERE.</div><h1 className="headline" style={{fontSize:105,marginTop:28,...reveal(f,5)}}>智能，不止于对话。</h1></div><div style={{position:'absolute',left:140,right:140,top:450,display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:23}}>{items.map((x,i)=><div className="card" key={x} style={{padding:'35px 33px',fontSize:32,fontWeight:600,display:'flex',alignItems:'center',gap:22,...reveal(f,14+i*7,45)}}><Icon name={(['logs','gear','spark','cube','pack','play'] as IconName[])[i]} size={32} color={i%2?PURPLE:'#54a4ff'}/>{x}</div>)}</div></AbsoluteFill>}
function End({f}:{f:number}){return <AbsoluteFill><Background f={f}/><div style={{position:'absolute',width:'100%',top:130,textAlign:'center'}}><Logo size={230} style={{...reveal(f,0),transform:`translateY(${lerp(25,0,out(f/40))}px) scale(${lerp(.9,1,out(f/42))})`}}/><div style={{fontSize:93,fontWeight:650,letterSpacing:-4,marginTop:35,...reveal(f,12)}}>Novaina <span className="gradient">Launcher</span></div><div style={{fontSize:44,fontWeight:600,marginTop:43,...reveal(f,25)}}>把想法，交给新星。</div><div style={{fontSize:23,color:'#96a4c0',letterSpacing:5,marginTop:36,...reveal(f,39)}}>VERSION 1.0.0</div></div><div style={{position:'absolute',bottom:57,left:0,width:'100%',textAlign:'center',fontSize:15,color:'#73829e',letterSpacing:1,opacity:out(at(f,58,82))}}>界面流程演示 · Music: Sam Gellaitry — Assumptions</div><AbsoluteFill style={{background:'#05070c',opacity:at(f,141,156)}}/></AbsoluteFill>}

const scenes=[{start:0,end:84,Comp:Intro},{start:84,end:228,Comp:Hero},{start:228,end:386,Comp:Overview},{start:386,end:530,Comp:Download},{start:530,end:703,Comp:Danmaku},{start:703,end:890,Comp:Skins},{start:890,end:991,Comp:AiReveal},{start:991,end:1193,Comp:AiPrompt},{start:1193,end:1351,Comp:AiQuestions},{start:1351,end:1553,Comp:AiExecute},{start:1553,end:1697,Comp:AiResult},{start:1697,end:1798,Comp:Capabilities},{start:1798,end:1950,Comp:End}];
export function Film(){const f=useCurrentFrame();const s=scenes.find(x=>f>=x.start&&f<x.end)||scenes[scenes.length-1];const Scene=s.Comp;return <AbsoluteFill className="film"><Scene f={f-s.start}/><Sequence from={0} durationInFrames={100}><Audio src={staticFile('intro-sfx.wav')} volume={.85}/></Sequence><Sequence from={84} durationInFrames={1866}><Audio src={staticFile('assumptions.mp3')} volume={af=>.78*Math.min(1,af/9)*Math.min(1,(1866-af)/66)}/></Sequence></AbsoluteFill>}
