<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
    <PackageReference Include="Downloader" Version="5.9.8" />
    <PackageReference Include="CmlLib.Core.Installer.Forge" Version="1.1.1" />
    <PackageReference Include="CmlLib.Core.Installer.NeoForge" Version="4.0.1" />
    <PackageReference Include="Tomlyn" Version="0.19.0" />
    <PackageReference Include="Semver" Version="3.0.0" />
    <PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.3.1" />
    <PackageReference Include="CmlLib.Core.Auth.Microsoft.MsalClient" Version="2.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.2" />
    <PackageReference Include="XboxAuthNet.Game.Msal" Version="0.1.3" />
  </ItemGroup>
  <ItemGroup Condition="'$(PublishSingleFile)' != 'true'">
    <Content Include="ThirdParty/**/LICENSE*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="ThirdParty/**/NEOFORGE-LICENSE*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
